### ISSUE TITLE
Not buildable locally

### ISSUE THREAD

**Issue by seppzer0** [Seshiria/op5dc#1]
Hi.
I've been trying to build your kernel locally, without the main.yml in in .github directory.

For a local build I changed `${GITHUB_WORKSPACE}` to `$(pwd)`.

And I've got a few problems:
1) `arch/arm64/Makefile:54: *** arm-linux-gnueabi-gcc not found, check CROSS_COMPILE_ARM32. Stop.`
Ok, I suppose gcc-arm-linux-gnueabi package was missing, so I ran a `sudo apt install -y gcc-arm-linux-gnueabi`.
Moving on..

2) `/bin/sh: 1: clang: not found`
That was a bit strange to me, because I thought android prebuilds already included `clang`.
Ok, I tried `sudo apt install -y clang`.
Moving on..

3) Finally, I got this:
`make[2]: *** [..././Kbuild:20: kernel/bounds.s] Error 1`
`make[1]: *** [/home/pc/Desktop/project/op5dc/kernel/Makefile:1077: prepare0] Error 2`
And a _lot_ of code-related errors.

The machine I use is the latest Ubuntu distro.

Could you provide some advice and/or comment on this?
I would like to build the kernel myself, and I don't understand how is it I can't do that, but there are ready .zip archives in the Release tab.

**Comment by Seshiria** [comment]
In order to facilitate debugging, the GitHub actions script in ``ci.sh`` ,You can find it in the repository root directory

You can check according to the following methods


 1. "Complete" clone this repository:
````
git clone --recursive $URL --depth=1
````
If you have clone repository,Please execute in the repository
````
git submodule init --depth=1
````
[reference ](https://git-scm.com/book/en/v2/Git-Tools-Submodules)

2 . Add the system PATH variable correctly:

Based on this repository:$(pwd)

````
 export PATH=${pwd}/android_prebuilts_build-tools/path/linux-x86/:$PATH
 export PATH=${pwd}/android_prebuilts_build-tools/linux-x86/bin/:$PATH
````

Finally, please run `` which clang ``, Check that clang is in the right place

**Comment by seppzer0** [comment]
1) I cloned your repo with a oneline `git clone https://github.com/Seshiria/op5dc --recurse-submodules --shallow-submodules`, all the submodules are already in place.

2) Also I've done the `$(pwd)` change, as I mentioned in my original comment.
All the `${GITHUB_WORKSPACE}` in ci.sh are changed to `$(pwd)`.

3) The `which clang` output is `/usr/bin/clang`

**Comment by Seshiria** [comment]
The commands to be executed should look like：
````
cd op5dc
sh ci.sh
````
If ``sh dir/ci.sh``, the environment variable is set incorrectly

**Comment by seppzer0** [comment]
Here's a piece of log:
```
make[1]: Entering directory '/home/cal/Desktop/project/op5dc/kernel/out'
/home/cal/Desktop/project/op5dc/kernel/Makefile:713: Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
/home/cal/Desktop/project/op5dc/kernel/Makefile:713: Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler
  CHK     include/config/kernel.release
  Using .. as source for kernel
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CC      kernel/bounds.s
In file included from ../kernel/bounds.c:9:
In file included from ../include/linux/page-flags.h:9:
In file included from ../include/linux/bug.h:4:
In file included from ../arch/arm64/include/asm/bug.h:67:
In file included from ../include/asm-generic/bug.h:13:
In file included from ../include/linux/kernel.h:13:
In file included from ../include/linux/printk.h:8:
In file included from ../include/linux/cache.h:5:
In file included from ../arch/arm64/include/asm/cache.h:19:
In file included from ../arch/arm64/include/asm/cachetype.h:19:
In file included from ../arch/arm64/include/asm/cputype.h:118:
../arch/arm64/include/asm/sysreg.h:254:43: error: value size does not match register size specified by the constraint and modifier [-Werror,-Wasm-operand-widths]
        asm volatile("mrs %0, sctlr_el1" : "=r" (val));
                                                 ^
../arch/arm64/include/asm/sysreg.h:254:20: note: use constraint modifier "w"
        asm volatile("mrs %0, sctlr_el1" : "=r" (val));
                          ^~
                          %w0
../arch/arm64/include/asm/sysreg.h:257:44: error: value size does not match register size specified by the constraint and modifier [-Werror,-Wasm-operand-widths]
        asm volatile("msr sctlr_el1, %0" : : "r" (val));
                                                  ^
../arch/arm64/include/asm/sysreg.h:257:31: note: use constraint modifier "w"
        asm volatile("msr sctlr_el1, %0" : : "r" (val));
                                     ^~
                                     %w0
2 errors generated.
make[2]: *** [.././Kbuild:20: kernel/bounds.s] Error 1
make[1]: *** [/home/cal/Desktop/project/op5dc/kernel/Makefile:1077: prepare0] Error 2
make[1]: Leaving directory '/home/cal/Desktop/project/op5dc/kernel/out'
make: *** [Makefile:152: sub-make] Error 2
dc build error
```

**Comment by Seshiria** [comment]
[ci-debug.sh.txt](https://github.com/Seshiria/op5dc/files/8501404/ci-debug.sh.txt)

Please put the above script in and``ci.sh`` the same directory, and then execute ``sh ci-debug.sh.txt``, post the running results. If there is privacy information, please pay attention to blocking

**Comment by seppzer0** [comment]
I found the problem.

I shouldn't have just changed all `${GITHUB_WORKSPACE}` to `$(pwd)`.
Because in different parts of ci.sh `$(pwd)` value is different.

Instead I created a `localpath` with persistent `$(pwd)` value.

So ci.sh looks like this:
```
#!/bin/bash
#for github actions
set -eu
localpath=$(pwd)
Initsystem(){
    sudo apt update && \
    sudo apt install -y \
        gcc \
        libssl-dev
    #ghttps://github.com/LineageOS/android_prebuilts_build-tools
    export PATH=${localpath}/android_prebuilts_build-tools/path/linux-x86/:$PATH
    export PATH=${localpath}/android_prebuilts_build-tools/linux-x86/bin/:$PATH
}

Patch(){
    cp -R ../drivers/* ./drivers/
    echo "CONFIG_FLICKER_FREE=y" >> arch/arm64/configs/lineage_oneplus5_defconfig
}
Releases(){
    #path to ./kernel/
    cp -f out/arch/arm64/boot/Image.gz-dtb ../AnyKernel3/Image.gz-dtb
    #一天可能提交编译多次
    #用生成的文件的MD5来区分每次生成的文件
    var=`md5sum ../AnyKernel3/Image.gz-dtb`
    md5tab=${var:0:5}
    kernelversion=`head -n 3 ${localpath}/kernel/Makefile|awk '{print $3}'|tr -d '\n'`
    buildtime=`date +%Y%m%d`
    bash ${localpath}/zip.sh ${1}-${kernelversion}_testbuild_${buildtime}_${md5tab}
}
#使用指定的anykernel配置文件
cp ${localpath}/anykernel.sh ${localpath}/AnyKernel3/anykernel.sh

Initsystem
mkdir releases
cd ./kernel/

#Write flag
touch localversion
cat >localversion<<EOF
~DCdimming-for-Seshiria
EOF

##dc patch
Patch
#llvm dc build
make -j$(nproc --all) O=out lineage_oneplus5_defconfig \
                        ARCH=arm64 \
                        SUBARCH=arm64
(make -j$(nproc --all) O=out \
                      ARCH=arm64 \
                      SUBARCH=arm64 \
                      CROSS_COMPILE=aarch64-linux-gnu- \
                      CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
                      PATH=${localpath}/llvm/bin:$PATH \
                      CC="clang"\
                      CXX=clang++ \
                      AR=llvm-ar \
                      NM=llvm-nm \
                      AS=llvm-as \
                      OBJCOPY=llvm-objcopy \
                      OBJDUMP=llvm-objdump \
                      STRIP=llvm-strip \
&& Releases "op5lin18.1-dc") || (echo "dc build error" && exit 1)
```

So now the kernel builds locally.

Thank you for your time though, I appreciate it :)

**Comment by Seshiria** [comment]
I forgot how much time had passed since I left to write this script,
The solution is not to modify ``ci.sh``

````
export GITHUB_WORKSPACE=${pwd}
sh ci.sh
````


I need to write this down in case I forget it again
