### ISSUE TITLE
DC控制器软件已经不支持lineageOS 20

### ISSUE THREAD

**Issue by daxiaamu** [Seshiria/op5dc#2]
包括其他Android 13系统都是一样的。点击switch就闪退

**Comment by Seshiria** [comment]
用这个版本试试：https://github.com/Seshiria/op5dc/releases/download/4.4.302v20230102/DC.Tuner.1.0.apk

**Comment by daxiaamu** [comment]
> 用这个版本试试：https://github.com/Seshiria/op5dc/releases/download/4.4.302v20230102/DC.Tuner.1.0.apk

确认可用，感谢
