### ISSUE TITLE
System corruption after installing LineageOS update

### ISSUE THREAD

**Issue by sal666** [Seshiria/op5dc#4]
Hi,
installing your kernel on a 5T has worked fine for me. Thanks a lot for your work.
I'm facing some problems when installing new LOS updates, thow.
After fresh installing LOS + MindTheGapps + ksu all worked fine since day 1. But after installing an update for LOS the system went mad. Google Play Services started crashing making the device unusable. It seems that most of Google apps and probably other system apps lost their permissions. Eventually I managed to almost fix that by reenabling their permissions, but location was not working well so I finally had to resort to restore factory settings. 

When it comes to updating LOS I've already tried 2 different strategies:
1. First time I installed LOS (without KSU). It worked fine for many months. Then I installed you KSU and worked fine for some weeks. Then after installing a LOS update from update app I rebooted and then Google Play Services started crashing. Then rebooted to install KSU but Google Play Services kept crashing. After reinstalling MindTheGapps the crash was solved but some apps had lost their permissions. After fixing the permissions mostly everything worked fine except for location. Google Maps worked fine most of the time with some casual quirks.
2. Next time I tried to install a LOS update I did it by downloading it to a PC and sideloading it + your KSU (same kernel version than updated LOS). I faced the same problems. Flashing again MindTheGapps solved Google Play Services but some apps needed to be reinstalled. The device was not working fine, thow. Again some Google apps lost their permissions and even after trying to fix that not everything was working fine, mainly location.

Now I've fully wiped the storage from TWRP and clean installed LOS20 20231010,  MindTheGapps and KSU op5lin20-dc-ksu11272-44302v20231009. Everything works fine.

What could I've done wrong when installing LOS updates? Are there any steps or method I should follow in order to safely apply LOS updates?

Manor thanks in advance

**Comment by Seshiria** [comment]
More logs are needed to determine the problem, can you provide the following logs?
1. logcat file when Google Play Services kept crashing
2. log when TWRP flash LOS

If the log file is too long, you can save it as a txt file and upload it here

Additional checks:
1, please check if the file "/system/addon.d/30-gapps.sh" or a similar filename exists
2. MindTheGapps version
4. List of modules enabled ksu
5. Please recall if any root software was used to modify gapps/system.

**Comment by sal666** [comment]
Sorry, I didn't save any logs. Will do next time.
Additional checks:
1. Yes, it exists
2. MindTheGapps-13.0.0-arm64
4. Modules: [Universal SafetyNet Fix](https://github.com/Displax/safetynet-fix/releases)  and [Zygisk on KernelSU](https://github.com/Dr-TSNG/ZygiskOnKernelSU/releases) 
5. No modifications done to gapps/system

**Comment by Seshiria** [comment]
> Sorry, I didn't save any logs. Will do next time. Additional checks:
> 
> 1. Yes, it exists
> 2. MindTheGapps-13.0.0-arm64
> 3. Modules: [Universal SafetyNet Fix](https://github.com/Displax/safetynet-fix/releases)  and [Zygisk on KernelSU](https://github.com/Dr-TSNG/ZygiskOnKernelSU/releases)
> 4. No modifications done to gapps/system

It looks like the addon.d of lineageos is malfunctioning, but it's not clear what's causing the problem. Please continue to test and keep the flash log in your next LOS update!

**Comment by sal666** [comment]
Are you referring to [this](https://gitlab.com/LineageOS/issues/android/-/issues/4976)?
This doesn't seem to be the cause because:
1. last script on /system/addon.d is V2
```shell
# grep VERSION /system/addon.d/*
/system/addon.d/30-gapps.sh:# ADDOND_VERSION=3
/system/addon.d/50-lineage.sh:# ADDOND_VERSION=2
``` 
2. I've never encountered this issue with stock LOS, before installing KernelSU

In any case, I'll try to install last update and see what happens.

**Comment by Seshiria** [comment]
>Are you referring to [this](https://gitlab.com/LineageOS/issues/android/-/issues/4976)?

I don't think it's this .Of course I can't be 100% sure without a log.

>I've never encountered this issue with stock LOS, before installing KernelSU

Theoretically, mindthegapps are maintained by automatically executing the sh under addon.d when Los is updated.
And op5lin20-dc-ksu11272-44302v20231009 is essentially an anykernel3 zip file. The main task is to flush the kernel into the corresponding /boot partition.It doesn't touch the /system partition or the gapps file.

Simple process to update Los:
1.flash Los.zip
2.addon executes, gapps.sh finishes its job
3.Finally manually flash op5lin20-dc-ksu
Where steps 1 and 2 are coherent and cannot be interrupted, so theoretically op5lin20-dc-ksu doesn't affect gapps.

So I need the log to determine which part is corrupted

**Comment by sal666** [comment]
I'm on TWRP. Can I sideload LOS 20231017 and then op5lin20-dc-ksu11272-44302v20231009.zip? Do we always need to install exactly same LOS and op5lin20-dc-ksu versions of they can differ?

**Comment by Seshiria** [comment]
> I'm on TWRP. Can I sideload LOS 20231017 and then op5lin20-dc-ksu11272-44302v20231009.zip? Do we always need to install exactly same LOS and op5lin20-dc-ksu versions of they can differ?

Yes, you can, usually just install the latest LOS and the latest op5lin20-dc kernel, e.g. currently LOS 20231016/20231017 (5/5T) and the latest op5lin20-dc (-ksu) 20231009.

Since the kernel may not have changed when the system was updated, it is possible to follow the previous version of the kernel .
A simple pairing:
1.correct: LOS 20231017 => op5lin20-dc 20231009
2 wrong:. LOS 20231003 < op5lin20-dc 20231009

**Comment by sal666** [comment]
Solved. It seems that the culprit was an old TWRP. I had version 3.5.1_9-0 and that version could not access local storage. I think it also showed some errors while trying to access data and system partitions.
I've now installed v3.7.0_12-1 and evening has changed. Now it asks for the password/pattern to decrypt user files. I've been able to download last LOS and KSU and install them with TWRP's install feature. Everything worked fine.
Many tanks for your help.

**Comment by Seshiria** [comment]
> Solved. It seems that the culprit was an old TWRP. I had version 3.5.1_9-0 and that version could not access local storage. I think it also showed some errors while trying to access data and system partitions. I've now installed v3.7.0_12-1 and evening has changed. Now it asks for the password/pattern to decrypt user files. I've been able to download last LOS and KSU and install them with TWRP's install feature. Everything worked fine. Many tanks for your help.

That's great, if you encounter the same problem you can reopen this issues
