### ISSUE TITLE
Request: kernel for LOS21+ksu

### ISSUE THREAD

**Issue by sal666** [Seshiria/op5dc#5]
Please, can you build the kernel for the new LOS21 with last KSU?
Many thanks in advance

**Comment by Seshiria** [comment]
I have not upgraded to Los21 yet due to personal issues, so please test for yourself.

Los21 kernelsu v0.8.0 actions : https://github.com/Seshiria/op5dc/actions/runs/8030264234

file : https://github.com/Seshiria/op5dc/actions/runs/8030264234/artifacts/1271926287

**Comment by sal666** [comment]
Awesome!! Thank you!!
Just installed. So far, evening seems to be working just fine.
![Android](https://github.com/Seshiria/op5dc/assets/8188625/4e0c681b-2aac-4c43-8c52-2d1c4a21a00d)
![KernelSU](https://github.com/Seshiria/op5dc/assets/8188625/ffcc0a35-49a9-46e6-a853-4cd1faaff966)
